# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos990-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter r8s x1s y2s z3s,$(TARGET_DEVICE)),)

endif
